### ISSUE TITLE
Restore GO support on Quest

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/Oculus#25]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Since the firmware updates on the Quest to default to run as an Oculus GO, XRTK doesn't run as default.  Granted the developer can simply configure the manifest and run in Quest mode, but this doesn't sit with XRTK's "Open -> Configure -> Run" ethos.

## How would you classify your suggestion

- New platform support
- Usability / Configuration

## Describe the solution you'd like

When I build a new solution for the Quest, It should both:

* Support the Oculus Go mode with controllers
* Run without having to configure the manifest

## Describe alternatives you've considered

Users have to manually force the Manifest update to get it to work.

## Additional context

Oculus recently updated the firmware on the Quest to support Oculus Go apps. sadly they made this the default option for any title running on the quest.

**Comment by SimonDarksideJ** [comment]
Hmm, not sure about this PR now as Oculus have officially discontinued the Go.  However, there are still a great many out there.
Thoughts @FejZa ?

**Comment by FejZa** [comment]
You might not like it but I think we don't need to worry about GO anymore. There is other frameworks/toolkits that can be used for GO development if needed.

I feel like 100% of XRTK users are targeting Quest. The next generation might even be revealed soon.

So as XRTK is still in heavy development let's cut these ties right now and not worry about GO.

**Comment by StephenHodgson** [comment]
If someone wants it they'll add it

**Comment by SimonDarksideJ** [comment]
You are thinking along the same lines I was thinking @FejZa , We'll leave it in the OpenVR space as it supports OpenVR, but we'll leave it out of the oculus package unless there is demand.

I recall that Oculus was potentially talking about removing it from the API entirely soon.
