### ISSUE TITLE
OVRControllerGamepadMac could not be found

### ISSUE THREAD

**Issue by wassx** [XRTK/Oculus#8]
## Describe the bug
I created a new blank project with latest xrtk packages installed.
Trying to build project console shows error:
`Library/PackageCache/com.xrtk.oculus@3ae186b0f5bc2ddcd455bd18dacc3620338f7268/OculusApi.cs(78,20): error CS0246: The type or namespace name 'OVRControllerGamepadMac' could not be found (are you missing a using directive or an assembly reference?)`

Removed and added all packages and installed Oculus Desktop/Android 1.38.1, still same error

## Information(please complete the following information):
 - Version: 2019.1.10f1 **MacOs**

**Comment by SimonDarksideJ** [comment]
For now, edit the OculusAPI.cs in the Oculus package and remove the following lines
```
#elif UNITY_STANDALONE_OSX || UNITY_EDITOR_OSX
			            new OVRControllerGamepadMac(),
#else
```
I'm checking through as to how the definition for missed as I thought I took everything across.
But XRTK isn't supported running on a Mac yet as a platform :D 
But something we can look in to
