### ISSUE TITLE
Update Oculus Plugin to v1.49

### ISSUE THREAD

**Issue by FejZa** [XRTK/Oculus#80]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

There is a new version of the Oculus plugin available which adds APIs to get dominant hand e.g.
XRTK should always look to get to the latest available and stable version as fast as possible.

**Comment by SimonDarksideJ** [comment]
Updated to 1.52, does that count :D Can you verify the API cal you required is included and close if good?

**Comment by FejZa** [comment]
Everything there for me that is currently needed.
