### ISSUE TITLE
Update Oculus integration to 15.1

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/Oculus#85]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Oculus just updated their API/Unity asset to a .1 release.  Would not usually trigger the need to update the API, however, the major note of this release is they added Oculus Quest 2 support.

**Comment by FejZa** [comment]
@SimonDarksideJ I think this can be closed as you updated the Oculus plugin recently?

**Comment by SimonDarksideJ** [comment]
You're right Dino.  Although there is probably another version out now ;)

**Comment by StephenHodgson** [comment]
I really wish they'd update to upm distribution
