### ISSUE TITLE
NRE on Oculus Package Assets import complete

### ISSUE THREAD

**Issue by FejZa** [XRTK/Oculus#92]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When importing Oculus Package assets a NRE is thrown once the import has finished.

```
NullReferenceException: Object reference not set to an instance of an object
XRTK.Editor.PackageInstaller.AddConfigurations (System.Collections.Generic.List`1[T] profiles) (at Library/PackageCache/com.xrtk.core@0.2.0-preview.127/Editor/PackageInstaller.cs:146)
XRTK.Editor.PackageInstaller+<>c__DisplayClass1_0.<TryInstallAssets>b__0 () (at Library/PackageCache/com.xrtk.core@0.2.0-preview.127/Editor/PackageInstaller.cs:125)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <a8e33794c0064f2aa201ade069162226>:0)
```

## To Reproduce

1. Install XRTK-Core via UPM
2. Install XRTK-SDK via UPM
3. Install XRTK-Oculus via UPM
4. Import SDK Package assets via `Mixed Reality Toolkit -> Packages -> Install XRTK.SDK Package Assets`
5. Confiture the scene via `Mixed Reality Toolkit -> Configure...`
6. Import Oculus Package assets via `MixedRealityToolkit -> Packages -> Install Oculus Package Assets`

NRE is thrown and logged once step 6 has completed.

## Expected behavior

No NRE thrown.

## Actual behavior

NRE thrown.

## Your Setup

- Windows 10
- Unity 2019.4.15f1
- XRTK 0.2 preview

**Comment by FejZa** [comment]
The exception seems to happen at
```
if (EditorUtility.DisplayDialog("We found a new Platform Configuration",
                    $"We found the {platformConfigurationProfile.name.ToProperCase()}. Would you like to add this platform configuration to your {rootProfile.name}?",
                    "Yes, Absolutely!",
                    "later"))```

Most likely the platformConfigurationProfile reference is null.

**Comment by FejZa** [comment]
I'll look into this

**Comment by SimonDarksideJ** [comment]
Odd, as I bring up that dialog all the time and don't get the issue.  But if you can replicate it, great and we can nail it down

**Comment by StephenHodgson** [comment]
@FejZa is this fixed now?

**Comment by FejZa** [comment]
Yes this is fixed
