### ISSUE TITLE
Oculus Camera Provider needs a default configuration with quality level set to medium

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/Oculus#94]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Currently, the default configuration for Oculus does not deploy a configuration profile for the Camera provider. This results in the user of the Default configuration supplied by the SDK.

However, Due to the current wireframe shader implementation, the Quest cannot run at the default "Ultra" quality setting that is defined by the Default camera configuration.  Thus, Oculus needs it's own default configuration setting the quality level to "Medium"

## To Reproduce

1. Create a project for Android to target the Oculus Quest
2. Build and try to deploy the project to Quest
3. Boom

## Expected behavior

Deployable builds for Android

## Actual behavior

Boom

## Your Setup

- Operation system - Android
- Unity Version 2019.4
- XRTK Version 0.2-preview

## Additional context

Known issue with the Wireframe shader, situation to also be reviewed once we move to URP,

**Comment by StephenHodgson** [comment]
Boom?

**Comment by StephenHodgson** [comment]
Just create a camera profile for the Oculus and set it in the camera data provider.

**Comment by SimonDarksideJ** [comment]
THat is what I intend to do, so it is set out of the box, instead of the user being hit with a build error

**Comment by FejZa** [comment]
Are you sure this is related to the graphics quality setting?

**Comment by SimonDarksideJ** [comment]
Absolutely.
![image](https://user-images.githubusercontent.com/1793042/100556232-d121c080-3298-11eb-8b02-6e7f47e3be05.png)
If the Quality setting is set to high or ultra, the wireframeshader fails to compile for Quest.  The same issue occurred on MRTK, albeit it did compile, but the display would not render when looking at an object with the wireframe shader attached.

In talking to Ronald at the time, this is a Unity limitation on Android due to some shader keywords.

A better fix would be to have a wireframe shader that worked better on Android / Quest, but this short term fix enables builds to load now.  The alternative is to simply delete the wireframeshader from the build.

**Comment by SimonDarksideJ** [comment]
Resolved
